language: cpp
os:
  - linux
  - osx

env:
  global:
    - MAKEFLAGS="-j 2"

before_install:
  - |
      if test x`uname` = x"Linux"; then
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
             texlive-fonts-recommended texlive-latex-extra \
             texlive-fonts-extra dvipng texlive-latex-recommended
      fi

install:
  - case $TRAVIS_OS_NAME in linux) OSNAME=Linux;; osx) OSNAME=MacOSX;; esac
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-$OSNAME-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PREFIX="$HOME/miniconda"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda config --add channels epruesse
  - conda install arb-bio boost gcc llvm pkg-config toolchain autoconf automake libtool
  - rm $PREFIX/bin/sed # temporary hackaround
  - export ARBHOME=`echo | arb shell | sed -n 's/.*ARBHOME='\''\(.*\)'\''/\1/p'`
  - export CFLAGS="$CFLAGS -I$PREFIX/include"
  - export LDFLAGS="$LDFLAGS -L$PREFIX/lib -Wl,-rpath,$PREFIX/lib"
  - export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig:$PREFIX/share/pkgconfig"
  
script:
  - sh autogen.sh
  - |
      case `uname` in
      Linux)  ./configure --with-arbhome=$ARBHOME --with-boost=$PREFIX \
              || cat config.log;
              ls /home/travis/miniconda/lib/arb/lib/
      ;;
      Darwin) ./configure --with-arbhome=$ARBHOME --with-boost=$PREFIX \
                          --disable-docs \
              || cat config.log
      ;;
      esac
      $? 
  - make
  - make check
  - test x`uname` = x"Linux" && make dist-gzip && make distcheck
  - make bindist-gzip

  
