language: cpp
os:
  - linux
  - osx
cache: ccache

install:
  - |
    case $TRAVIS_OS_NAME in
      linux)
        conda_OSNAME=Linux
        OSNAME=linux
      ;;
      osx)
        conda_OSNAME=MacOSX
        OSNAME=macos
        ;;
      esac
  - |
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-$conda_OSNAME-x86_64.sh -O miniconda.sh;
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"'
    export PREFIX="$HOME/miniconda"
    hash -r
    conda config --set always_yes yes --set changeps1 no
    conda update -q conda
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda create -n build arb-bio boost pkg-config autoconf automake libtool
  - source activate build
  - export CFLAGS="$CFLAGS -I$PREFIX/include"
  - export LDFLAGS="$LDFLAGS -L$PREFIX/lib -Wl,-rpath -Wl,$PREFIX/lib"
  - export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig:$PREFIX/share/pkgconfig"

script:
  - sh autogen.sh
  - ./configure --with-arbhome=$ARBHOME \
                --with-boost=$PREFIX \
                --enable-fat-tar \
                --disable-docs \
                || cat config.log
       ;;
  - make -j2
  - if test `uname` = Linux; then make check V=1; fi
  - make bindist-gzip
  - if test `uname` = Linux; then make dist-gzip && make distcheck; fi
  - mkdir install
  - cd install
  - tar -xvzf ../sina-*-$OSNAME.tar.gz
  - ./sina --has-cli-vers 2

deploy:
  provider: releases
  api_key:
    secure: PAMAHWSFyRawrBjfsQiQxXvjWm85kZWsBn3MZ87ZIsIFLJxsd5JDl1V3VLYbDqo2v2GYXx1Ew9fkffr9O76XdWwdY0OCUn1P7jBcJXSiLKAQUS7agyV3U0H4gVu2Ghyrr3qiNNLPbKij8iXmKKoqgYq1PXAXzn6d9rqc0Cloh8gxhlhjAJAJfMchbeTaf6VulIpSk0hlFIvDhPXqpQ/Nrrac3c4aVn3CIC0TVcy8hMFjPNiLio5Vxj3XT5UjJChen8Af3sm1Kj+HzgyYzNHuCJ5sBw5kqh2gKlTvFyl9SOcludVAPRIHquJ5pmp8+EPJ6Yv0upe4QrdnJh6nGAZTkXbAb2VqOaZqR53w+F0+EsQqzkAnFCTJPfUco4yS41H6880gJTuONcWyQWyLgvNp43aK26rADfGlBf6O3p5upm9VyktpR/y2UWtWZZgoHjDMty9QNKd1vpUwr7gySU5nkYlBoixhJ6+qfhufuAcF6Btxll1ypIfbifPcGCeqQ5s2qGfuPJ7sRrB1KlpzttcmBHj5qidWSqktqQ3DnlSv3RCc10dE/iU+AngdO+3xaLax4dnlzA1/kbHmTHJVOzkXvec/lbF725fTqK9sJNa11a7HIG4mtg+8ywclDyESISUS5HWD3ejvbBOsKdq3dP7SFQg0nmHsvXcK+y3JESuDK/Q=
  file_glob: true
  file: sina-*.tar.gz
  skip_cleanup: true
  on:
    repo: epruesse/SINA
    tags: true
