language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

install:
  - case $TRAVIS_OS_NAME in linux) OSNAME=Linux;; osx) OSNAME=MacOSX;; esac
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-$OSNAME-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PREFIX="$HOME/miniconda"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda config --add channels epruesse
  - conda install arb-bio boost gcc llvm
  - rm $PREFIX/bin/sed # temporary hackaround
  - export ARBHOME=`echo | arb shell | sed -n 's/.*ARBHOME='\''\(.*\)'\''/\1/p'`
  - export CFLAGS="$CFLAGS -I$PREFIX/include"
  - export LDFLAGS="$LDFLAGS -L$PREFIX/lib"
  - export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig:$PREFIX/share/pkgconfig"
  
script:
  - sh autogen.sh
  - ./configure --with-arbhome=$ARBHOME || cat config.log
  - make
  - make install
  