language: cpp
compiler:
  - gcc
  - clang

os:
  - linux

before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y arb
script:
  - sh autogen.sh
  - ./configure --with-arbhome=/usr/lib/arb
  - make
  - make install
  